#!/usr/bin/env python3
"""Build the province outlines the portal draws its choropleth with.

    python3 scripts/province-shapes.py

Source: github.com/ardian28/GeoJson-Indonesia-38-Provinsi (MIT), from BIG's
geoservice — the same redistribution reference/geography/indonesia-regencies.csv
takes its attributes from. The polygons are a drawing, not reference data: they
are simplified to a few per cent of their vertices, islands under 40 km² are
dropped, and they are written as SVG paths in a fixed equirectangular frame.
Nothing in the warehouse joins on them.

It also writes reference/geography/indonesia-provinces.geojson: the same
outlines kept as polygons and simplified less, keyed by geo_id. That one is
what the Earth Engine air-quality source averages over, so it keeps every
island — a province's small islands are part of its air — and only enough
vertices to stay small enough to send inline with a request.

The source's KODE_PROV is stale for the 2022 Papua splits (four provinces carry
91), so each outline is keyed by name against indonesia-provinces.csv instead.
"""

import csv
import json
import subprocess
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = (
    "https://raw.githubusercontent.com/ardian28/GeoJson-Indonesia-38-Provinsi/"
    "main/Provinsi/38%20Provinsi%20Indonesia%20-%20Provinsi.json"
)
OUT = ROOT / "apps/portal/src/lib/indonesia-provinces.ts"
GEOJSON = ROOT / "reference/geography/indonesia-provinces.geojson"

# The frame: Sabang to Merauke, Miangas to Rote, at 20 px a degree.
WEST, EAST, NORTH, SOUTH = 94.8, 141.2, 6.2, -11.2
SCALE = 20


def registry() -> dict[str, tuple[str, str]]:
    path = ROOT / "reference/geography/indonesia-provinces.csv"
    rows = csv.DictReader(line for line in path.open() if not line.startswith("#"))
    names: dict[str, tuple[str, str]] = {}
    for row in rows:
        if row["geo_type"] != "province":
            continue
        for name in [row["name"], *row["aliases"].split("|")]:
            names[name.lower()] = (row["geo_id"], row["name"])
    return names


def path_of(geometry: dict) -> str:
    polygons = (
        geometry["coordinates"]
        if geometry["type"] == "MultiPolygon"
        else [geometry["coordinates"]]
    )
    parts = []
    for polygon in polygons:
        for ring in polygon:
            points = [
                (round((x - WEST) * SCALE, 1), round((NORTH - y) * SCALE, 1))
                for x, y in ring
            ]
            kept = [points[0]] + [p for i, p in enumerate(points[1:], 1) if p != points[i - 1]]
            if len(kept) < 4:
                continue
            parts.append("M" + "L".join(f"{x:g} {y:g}" for x, y in kept[:-1]) + "Z")
    return "".join(parts)


def write_regions(features: list[dict], names: dict[str, tuple[str, str]]) -> None:
    keyed = sorted(
        (names[f["properties"]["PROVINSI"].lower()], f["geometry"]) for f in features
    )
    collection = {
        "type": "FeatureCollection",
        "features": [
            {"type": "Feature", "properties": {"geo_id": g, "name": n}, "geometry": geometry}
            for (g, n), geometry in keyed
        ],
    }
    GEOJSON.write_text(json.dumps(collection, separators=(",", ":")) + "\n")
    print(f"wrote {len(keyed)} provinces to {GEOJSON.relative_to(ROOT)}")


def main() -> None:
    names = registry()
    with tempfile.TemporaryDirectory() as scratch:
        raw, simple = Path(scratch, "raw.json"), Path(scratch, "simple.json")
        subprocess.run(["curl", "-sSfL", "-o", str(raw), SOURCE], check=True)
        subprocess.run(
            ["npx", "-y", "mapshaper", str(raw),
             "-simplify", "7%", "keep-shapes",
             "-filter-islands", "min-area=40km2",
             "-o", "format=geojson", "precision=0.001", str(simple)],
            check=True,
        )
        features = json.loads(simple.read_text())["features"]

        regions = Path(scratch, "regions.json")
        subprocess.run(
            ["npx", "-y", "mapshaper", str(raw),
             "-simplify", "20%", "keep-shapes",
             "-o", "format=geojson", "precision=0.001", str(regions)],
            check=True,
        )
        write_regions(json.loads(regions.read_text())["features"], names)

    shapes = sorted(
        (*names[f["properties"]["PROVINSI"].lower()], path_of(f["geometry"]))
        for f in features
    )
    width = round((EAST - WEST) * SCALE)
    height = round((NORTH - SOUTH) * SCALE)
    lines = [
        "// Generated by scripts/province-shapes.py — do not edit by hand.",
        "// Outlines: github.com/ardian28/GeoJson-Indonesia-38-Provinsi (MIT), from BIG.",
        "",
        "export type ProvinceShape = { geo_id: string; name: string; d: string };",
        "",
        f"export const PROVINCE_FRAME = {{ width: {width}, height: {height} }} as const;",
        "",
        "export const PROVINCE_SHAPES: ProvinceShape[] = [",
        *(f"  {{ geo_id: {json.dumps(g)}, name: {json.dumps(n)}, d: {json.dumps(d)} }},"
          for g, n, d in shapes),
        "];",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {len(shapes)} provinces to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
